---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  interval: 1h
  values:
    alertmanager:
      alertmanagerSpec:
        alertmanagerConfiguration:
          name: alertmanager
        externalUrl: "https://${ALERTMANAGER_HOSTNAME:=alertmanager}.${SECRET_DOMAIN}"
        replicas: ${ALERTMANAGER_REPLICAS:=1}
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
              storageClassName: miroir-local
      route:
        main:
          enabled: true
          hostnames:
            - "${ALERTMANAGER_HOSTNAME:=alertmanager}.${SECRET_DOMAIN}"
          parentRefs:
            - name: envoy-internal
              namespace: network
    cleanPrometheusOperatorObjectNames: true
    grafana:
      enabled: false
      forceDeployDashboards: true
      operator:
        dashboardsConfigMapRefEnabled: true
        folder: Observability
        matchLabels:
          dashboards: grafana
    kubeEtcd:
      service:
        selector:
          component: kube-apiserver # etcd runs on control plane nodes
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: false
    prometheus-node-exporter:
      fullnameOverride: node-exporter
    prometheus:
      prometheusSpec:
        externalUrl: "https://${HOSTNAME:=prometheus}.${SECRET_DOMAIN}"
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        replicas: ${REPLICAS:=1}
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
        retention: 30d
        retentionSize: 50GB
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 50Gi
              storageClassName: miroir-local
      route:
        main:
          enabled: true
          hostnames:
            - "${HOSTNAME:=prometheus}.${SECRET_DOMAIN}"
          parentRefs:
            - name: envoy-internal
              namespace: network
