---
# Areas
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file:
          - bootstrap/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - kubernetes/**/*
area/talos:
  - changed-files:
      - any-glob-to-any-file:
          - talos/**/*
