---
# Areas
- name: area/bootstrap
  color: "0E8A16"
  description: >-
    Changes made in the bootstrap directory
- name: area/docs
  color: "0E8A16"
  description: >-
    Changes made in the docs directory
- name: area/github
  color: "0E8A16"
  description: >-
    Changes made in the github directory
- name: area/kubernetes
  color: "0E8A16"
  description: >-
    Changes made in the kubernetes directory
- name: area/renovate
  color: "0E8A16"
  description: >-
    Changes made to the Renovate files
- name: area/talos
  color: "0E8A16"
  description: >-
    Changes made in the talos directory
# Renovate Types
- name: action/automerge
  color: "5319E7"
  description: >-
    PR that has been automerged by Renovate
# Semantic Types
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
