---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: picard
spec:
  chartRef:
    kind: OCIRepository
    name: picard
  interval: 1h
  values:
    controllers:
      picard:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              DARK_MODE: "1"
              GROUP_ID: ${APP_PGID:=1000}
              TZ: "${CLUSTER_TIME_ZONE}"
              USER_ID: ${APP_PUID:=1000}
              WEB_AUDIO: "1"
              WEB_LISTENING_PORT: &port 5800
            image:
              repository: ghcr.io/jlesage/musicbrainz-picard
              tag: v26.03.1@sha256:661b1e04ee873f527345d280d27ed60873649af5691b47aed0b758dd6f931b72
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 10m
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   capabilities:
            #     drop:
            #       - "ALL"
            #   readOnlyRootFilesystem: true
        replicas: ${REPLICAS:=1}
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      securityContext:
        fsGroup: ${APP_PGID:=1000}
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: ${APP_PGID:=1000}
        runAsUser: ${APP_PUID:=1000}
    persistence:
      config:
        existingClaim: "${VOLSYNC_PVC:=${APP}}"
        globalMounts:
          - path: /config
      nas-data:
        advancedMounts:
          picard:
            app:
              - path: /storage
                subPath: media/audio
                readOnly: true
        path: "${NFS_DATA_PATH}"
        server: "${NAS_ADDRESS}"
        type: nfs
    route:
      app:
        hostnames:
          - "${HOSTNAME:=${APP}}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
