[env]
# file paths
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/infrastructure/talos/clusterconfig/talosconfig"

# dotenv
_.file = ["{{config_root}}/.secrets.env"]

# python
# _.python.venv = { path = "{{config_root}}/.venv", create = true }

# just
JUST_UNSTABLE = "1"

# lefthook
# LEFTHOOK_OUTPUT = "false"

[tools]
# kubernetes
"aqua:helm/helm" = "4.2.0"
"aqua:helmfile/helmfile" = "1.4.4"
"aqua:kubernetes-sigs/kustomize" = "5.8.1"
"aqua:kubernetes/kubernetes/kubectl" = "1.35.4"
"aqua:siderolabs/talos" = "1.12.7"

# misc
"aqua:casey/just" = "1.48.1"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:evilmartians/lefthook" = "2.1.9"
"aqua:fluxcd/flux2" = "2.8.5"
"aqua:helmfile/vals" = "0.44.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:mikefarah/yq" = "4.53.2"
"aqua:mitsuhiko/minijinja" = "2.19.0"
"aqua:zizmorcore/zizmor" = "1.25.2"
"npm:oxfmt" = "0.52.0"

[hooks]
postinstall = ["lefthook install"]
