---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garage-operator
  namespace: &namespace storage
spec:
  interval: 1h
  path: ./kubernetes/apps/storage/garage/operator
  prune: true
  postBuild:
    substitute:
      REPLICAS: "1"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage-gateway
  namespace: &namespace storage
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: garage-operator
      namespace: *namespace
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  interval: 1h
  path: ./kubernetes/apps/storage/garage/gateway
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_PVC: "metadata-garage-gateway-0"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
