---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidusergroup_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: paperless-users
spec:
  friendlyName: Paperless Users
  name: paperless_users
  users:
    usernames:
      - cburnham
