---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rajsinghtech/garage-operator/main/schemas/garagebucket_v1beta1.json
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: pocket-id-files
spec:
  clusterRef:
    name: garage-gateway
    namespace: storage
  quotas:
    maxSize: 8Gi
