# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file           :   inventory/hosts.yml
#   @description    :   ansible inventory
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
# --------------------------------------------------------------------------------------------------
# all hosts
# --------------------------------------------------------------------------------------------------
all:
  hosts:
    captain:
# ==================================================================================================

# --------------------------------------------------------------------------------------------------
# synology hosts
# --------------------------------------------------------------------------------------------------
synology:
  hosts:
    captain:
# ==================================================================================================
