---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  chartRef:
    kind: OCIRepository
    name: gatus
  interval: 1h
  values:
    controllers:
      gatus:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              GATUS_CONFIG_PATH: /config
              GATUS_DELAY_START_SECONDS: 5
              GATUS_WEB_PORT: &port 80
              TZ: "${CLUSTER_TIME_ZONE}"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            image:
              repository: ghcr.io/twin/gatus
              tag: v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 10m
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true
        initContainers:
          gatus-sidecar:
            args:
              - --auto-httproute
              - --enable-httproute
              - --enable-service
            image:
              repository: ghcr.io/home-operations/gatus-sidecar
              tag: 0.3.6@sha256:195e761e2fcf65bc959bea55f2ed15cdada44cc6653af6dc117b6241b010015b
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 10m
            restartPolicy: Always
          init-db:
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 17.4@sha256:43dd04e91e861cf912378bad987afa168fa4f13d05528304907ad0aa351195d6
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      automountServiceAccountToken: true
      securityContext:
        runAsGroup: ${APP_PGID:=1000}
        runAsNonRoot: true
        runAsUser: ${APP_PUID:=1000}
    persistence:
      config:
        type: emptyDir
      config-file:
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
        name: "{{ .Release.Name }}-configmap"
        type: configMap
    rbac:
      bindings:
        gatus:
          roleRef:
            kind: ClusterRole
            name: gatus
          subjects:
            - identifier: gatus
          type: ClusterRoleBinding
      roles:
        gatus:
          rules:
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - get
                - watch
                - list
            - apiGroups:
                - gateway.networking.k8s.io
              resources:
                - gateways
                - httproutes
              verbs:
                - get
                - watch
                - list
          type: ClusterRole
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames:
          - "${HOSTNAME:=${APP}}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
    serviceAccount:
      gatus: {}
    serviceMonitor:
      app:
        endpoints:
          - port: http
