---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
spec:
  dataFrom:
    - extract:
        key: seerr
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seerr-secret
    template:
      data:
        API_KEY: "{{ .SEERR_API_KEY }}"
