---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  chartRef:
    kind: OCIRepository
    name: seerr
  interval: 1h
  values:
    controllers:
      seerr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              LOG_LEVEL: "info"
              PORT: &port 80
              TZ: "${CLUSTER_TIME_ZONE}"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: v3.1.0@sha256:b35ba0461c4a1033d117ac1e5968fd4cbe777899e4cbfbdeaf3d10a42a0eb7e9
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 5
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 10m
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true
        replicas: ${REPLICAS:=1}
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      securityContext:
        fsGroup: ${APP_PGID:=1000}
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: ${APP_PGID:=1000}
        runAsNonRoot: true
        runAsUser: ${APP_PUID:=1000}
    persistence:
      config:
        existingClaim: "${VOLSYNC_PVC:=${APP}}"
        globalMounts:
          - path: /app/config
      tmpfs:
        advancedMounts:
          seerr:
            app:
              - path: /tmp
                subPath: tmp
        type: emptyDir
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
          - "${HOSTNAME:=${APP}}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
