---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app seerr
  namespace: &namespace default
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: volsync
      namespace: storage
  interval: 1h
  path: ./kubernetes/apps/default/seerr/app
  postBuild:
    substitute:
      APP: *app
      HOSTNAME: requests
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false # no flux ks dependents
