---
connectivity:
  checker:
    interval: 1m
    target: 1.1.1.1:53
endpoints:
  - name: Cloudflare
    conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    url: icmp://1.1.1.1
  - name: Google
    conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    url: icmp://8.8.8.8
  - name: Quad9
    conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    url: icmp://9.9.9.9
metrics: true
storage:
  caching: true
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  type: postgres
ui:
  buttons:
    - name: Github
      link: https://github.com/blthazr
    - name: Homelab
      link: https://github.com/blthazr/area0
  header: Status
  link: https://github.com/blthazr
  logo: https://avatars.githubusercontent.com/u/16470300
  title: Status | Gatus
web:
  port: ${GATUS_WEB_PORT}
