# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file           :   inventory/group_vars/all/global.yml
#   @description    :   global variables
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
# --------------------------------------------------------------------------------------------------
# locale settings
# --------------------------------------------------------------------------------------------------
# -- (str) timezone for the site
timezone: "America/Chicago"
# ==================================================================================================
