---
# TODO: yaml-language-server: $schema=
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
spec:
  enabled: true
  moverVolumes:
    - mountPath: repository
      volumeSource:
        nfs:
          path: "${NFS_DATA_PATH}/backup/kopia"
          server: "${NAS_ADDRESS}"
  repository:
    repository: volsync-maintenance-secret
  trigger:
    schedule: 30 3,15 * * *
