[env]
# file paths
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/infrastructure/talos/clusterconfig/talosconfig"

# dotenv
_.file = ["{{config_root}}/.onepassword.env", "{{config_root}}/.secrets.env"]

# just
JUST_UNSTABLE = "1"

[tools]
# kubernetes
"aqua:helm/helm" = "4.2.2"
"aqua:helmfile/helmfile" = "1.6.0"
"aqua:helmfile/vals" = "0.44.3"
"aqua:kubernetes-sigs/kustomize" = "5.8.1"
"aqua:kubernetes/kubernetes/kubectl" = "1.36.2"
"aqua:siderolabs/talos" = "v1.12.7"

# misc
"aqua:casey/just" = "1.55.0"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:evilmartians/lefthook" = "2.1.9"
"aqua:fluxcd/flux2" = "2.8.8"
"aqua:jqlang/jq" = "1.8.2"
"aqua:mikefarah/yq" = "4.53.3"
"aqua:mitsuhiko/minijinja" = "2.21.0"
"npm:oxfmt" = "0.59.0"

[hooks]
postinstall = ["lefthook install"]
