---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo
spec:
  chartRef:
    kind: OCIRepository
    name: echo
  interval: 1h
  values:
    controllers:
      echo:
        containers:
          app:
            env:
              HTTP_PORT: &port 80
              LOG_IGNORE_PATH: /healthz
              LOG_WITHOUT_NEWLINE: true
              PROMETHEUS_ENABLED: true
            image:
              repository: ghcr.io/mendhak/http-https-echo
              tag: 40
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              limits:
                memory: 64Mi
              requests:
                cpu: 10m
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true
        replicas: ${REPLICAS:=1}
        strategy: RollingUpdate
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      securityContext:
        runAsGroup: ${APP_PGID:=1000}
        runAsNonRoot: true
        runAsUser: ${APP_PUID:=1000}
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - "${HOSTNAME:=${APP}}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
