---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cribl-leader
spec:
  data:
    - secretKey: CRIBL_LEADER_PASSWORD
      remoteRef:
        key: cribl
        property: CRIBL_LEADER_PASSWORD
    - secretKey: CRIBL_LEADER_TOKEN
      remoteRef:
        key: cribl
        property: CRIBL_LEADER_TOKEN
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cribl-leader-secret
    template:
      data:
        CRIBL_LEADER_PASSWORD: "{{ .CRIBL_LEADER_PASSWORD }}"
        CRIBL_LEADER_TOKEN: "{{ .CRIBL_LEADER_TOKEN }}"
