---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cribl-stream-workergroup
spec:
  chart:
    spec:
      chart: logstream-workergroup
      sourceRef:
        kind: HelmRepository
        name: cribl-stream-workergroup
        namespace: observability
      version: 4.18.1
  interval: 1h
  values:
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
    config:
      group: default
      host: cribl-leader-internal
      token: "${CRIBL_LEADER_TOKEN}"
    criblImage:
      repository: cribl/cribl
      tag: 4.14.0@sha256:01d39c97feb57e0046bd854508f7cbed581bdccff86cc977fc99016ee59fe1b6
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 256Mi
    service:
      loadBalancerIP: "${SVC_CRIBL_WORKER}"
      ports:
        - name: syslog-tcp
          port: 9514
          protocol: TCP
        - name: syslog-udp
          port: 9514
          protocol: UDP
        - name: syslog-unifi
          port: 9520
          protocol: UDP
        - name: splunk-hec
          port: 8088
          protocol: TCP
        - name: s2s
          port: 9997
          protocol: TCP
        - name: cribl-http
          port: 10200
          protocol: TCP
        - name: cribl-tcp
          port: 10300
          protocol: TCP
      type: LoadBalancer
