---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request Labeler

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main:
    name: Update Pull Request Labels
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets
        id: load-secrets
        uses: 1password/load-secrets-action@3a12b0ab99d9cd590a3e9b5a90ea017210ed9556 # v4.0.1 # zizmor: ignore[unpinned-tools]
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_BOT_APP_CLIENT_ID: op://area0/github-bot/GITHUB_BOT_APP_CLIENT_ID
          GITHUB_BOT_APP_PRIVATE_KEY: op://area0/github-bot/GITHUB_BOT_APP_PRIVATE_KEY

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ steps.load-secrets.outputs.GITHUB_BOT_APP_CLIENT_ID }}
          permission-issues: write
          permission-pull-requests: write
          private-key: ${{ steps.load-secrets.outputs.GITHUB_BOT_APP_PRIVATE_KEY }}

      - name: Run labeler
        uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
        with:
          configuration-path: .github/labeler.yaml
          repo-token: ${{ steps.app-token.outputs.token }}
