---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliumbgpadvertisement_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: l3-bgp-advertisement
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: Service
      selector:
        matchExpressions:
          - key: somekey
            operator: NotIn
            values:
              - never-used-value
      service:
        addresses:
          - LoadBalancerIP
