---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: kube-api
  annotations:
    lbipam.cilium.io/ips: "${SVC_K8S_API}"
spec:
  externalTrafficPolicy: Local
  ports:
    - name: https
      port: 6443
      protocol: TCP
      targetPort: 6443
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  type: LoadBalancer
